export const themes = {
  notion: {
    theme: {
      "--an-font-family": "system-ui, sans-serif",
      "--an-font-weight": "400",
      "--an-font-weight-medium": "500",
      "--an-font-weight-semibold": "600",
      "--an-text-size": "14px",
      "--an-text-size-sm": "13px",
      "--an-text-size-xs": "11px",
      "--an-line-height": "1.6",
      "--an-border-radius": "16px",
      "--an-message-border-radius": "16px",
      "--an-input-border-radius": "16px",
      "--an-input-inner-border-radius": "8px",
      "--an-send-button-border-radius": "9999px",
      "--an-stop-button-border-radius": "9999px",
      "--an-mode-selector-border-radius": "8px",
      "--an-tool-border-radius": "8px",
      "--an-code-border-radius": "8px",
      "--an-attachment-border-radius": "8px",
      "--an-message-gap": "8px",
      "--an-user-message-padding": "10px 14px",
      "--an-input-padding": "12px 16px",
      "--an-tool-padding": "8px 12px",
      "--an-code-padding": "16px",
      "--an-send-button-size": "32px",
      "--an-stop-button-size": "32px",
      "--an-scrollbar-width": "6px",
      "--an-input-font-size": "14px",
      "--an-date-divider-font-size": "11px",
      "--an-model-selector-font-size": "12px",
      "--an-tool-font-size": "13px",
      "--an-code-font-size": "13px",
      "--an-code-font-family": "ui-monospace, monospace",
      "--an-attachment-font-size": "12px",
      "--an-message-style": "bubble-right",
      "--an-message-density": "compact",
      "--an-input-style": "rounded",
      "--an-send-button-style": "circle-icon",
      "--an-stop-button-style": "circle-square",
      "--an-sticky-user-messages": "false",
      "--an-show-date-divider": "true",
      "--an-show-copy-button": "true",
      "--an-text-contrast": "normal",
      "--an-input-placeholder": "Do anything with AI...",
      "--an-attachment-button-style": "plus-circle",
      "--an-attachment-preview-style": "thumbnail",
      "--an-tool-call-style": "normal",
      "--an-thinking-display": "collapsed",
      "--an-code-action-display": "minimal",
      "--an-bash-display": "minimal",
      "--an-search-display": "rich-group",
      "--an-show-tool-icons": "true",
      "--an-message-shadow": "false",
      "--an-input-fill": "false",
      "--an-input-shadow-toggle": "true",
      "--an-show-window-chrome": "false",
      "--an-max-width": "420px",
      "--an-attachment-button-position": "left",
      "--an-model-selector-position": "input-bar",
      "--an-model-selector-side": "right",
      "--an-mode-selector-position": "popover",
    },
    light: {
      "--an-background": "#ffffff",
      "--an-background-secondary": "#f0f0f0",
      "--an-background-tertiary": "#f8f8f8",
      "--an-foreground": "#1a1a1a",
      "--an-foreground-muted": "#737373",
      "--an-foreground-subtle": "#a3a3a3",
      "--an-border-color": "#e4e4e7",
      "--an-border-color-light": "#ededf0",
      "--an-message-shadow": "none",
      "--an-user-message-bg": "#f5f5f5",
      "--an-user-message-text": "#1a1a1a",
      "--an-date-divider-color": "#a3a3a3",
      "--an-date-divider-border-color": "#ededf0",
      "--an-input-background": "transparent",
      "--an-input-border-color": "#e4e4e7",
      "--an-input-color": "#1a1a1a",
      "--an-input-placeholder-color": "#a3a3a3",
      "--an-input-shadow": "0 1px 3px 0 rgba(0,0,0,0.04)",
      "--an-stop-button-color": "#ffffff",
      "--an-stop-button-bg": "#1a1a1a",
      "--an-mode-selector-background": "#f0f0f0",
      "--an-mode-selector-color": "#737373",
      "--an-mode-selector-active-color": "#1a1a1a",
      "--an-mode-selector-active-background": "#ffffff",
      "--an-model-selector-color": "#737373",
      "--an-model-selector-hover-color": "#1a1a1a",
      "--an-tool-background": "#f8f8f8",
      "--an-tool-border-color": "#e4e4e7",
      "--an-tool-color": "#1a1a1a",
      "--an-tool-color-muted": "#737373",
      "--an-tool-icon-color": "#737373",
      "--an-code-background": "#1e1e1e",
      "--an-code-color": "#d4d4d4",
      "--an-attachment-background": "#f0f0f0",
      "--an-attachment-border-color": "#e4e4e7",
      "--an-attachment-hover-background": "#ebebeb",
      "--an-attachment-color": "#1a1a1a",
      "--an-attachment-color-muted": "#737373",
      "--an-scrollbar-color": "rgba(0,0,0,0.12)",
      "--an-scrollbar-hover-color": "rgba(0,0,0,0.2)",
      "--an-primary-color": "#ef4444",
      "--an-primary-color-hover": "#d23c3c",
      "--an-primary-color-active": "#bf3636",
      "--an-focus-color": "#ef4444",
      "--an-send-button-color": "#1a1a1a",
      "--an-send-button-bg": "#ef4444",
      "--an-send-button-hover-color": "#1a1a1a",
      "--an-send-button-hover-bg": "#d23c3c",
      "--an-send-button-active-bg": "#bf3636",
      "--an-send-button-shadow": "none",
      "--an-input-focus-border-color": "#ef4444",
      "--an-input-focus-shadow": "0 0 0 2px #ef44441a",
      "--an-diff-added-bg": "rgba(34, 197, 94, 0.1)",
      "--an-diff-added-border": "rgba(34, 197, 94, 0.5)",
      "--an-diff-added-text": "#15803d",
      "--an-diff-removed-bg": "rgba(239, 68, 68, 0.1)",
      "--an-diff-removed-border": "rgba(239, 68, 68, 0.5)",
      "--an-diff-removed-text": "#dc2626",
    },
    dark: {
      "--an-background": "#0a0a0a",
      "--an-background-secondary": "#242424",
      "--an-background-tertiary": "#141414",
      "--an-foreground": "#fafafa",
      "--an-foreground-muted": "#8c8c8c",
      "--an-foreground-subtle": "#71717a",
      "--an-border-color": "#2a2a2a",
      "--an-border-color-light": "#1f1f1f",
      "--an-message-shadow": "none",
      "--an-user-message-bg": "#242424",
      "--an-user-message-text": "#ffffff",
      "--an-date-divider-color": "#71717a",
      "--an-date-divider-border-color": "#1f1f1f",
      "--an-input-background": "transparent",
      "--an-input-border-color": "#2a2a2a",
      "--an-input-color": "#fafafa",
      "--an-input-placeholder-color": "#71717a",
      "--an-input-shadow": "0 1px 3px 0 rgba(0,0,0,0.4)",
      "--an-stop-button-color": "#0a0a0a",
      "--an-stop-button-bg": "#fafafa",
      "--an-mode-selector-background": "#242424",
      "--an-mode-selector-color": "#8c8c8c",
      "--an-mode-selector-active-color": "#fafafa",
      "--an-mode-selector-active-background": "#141414",
      "--an-model-selector-color": "#8c8c8c",
      "--an-model-selector-hover-color": "#fafafa",
      "--an-tool-background": "#141414",
      "--an-tool-border-color": "#2a2a2a",
      "--an-tool-color": "#fafafa",
      "--an-tool-color-muted": "#8c8c8c",
      "--an-tool-icon-color": "#8c8c8c",
      "--an-code-background": "#0a0a0a",
      "--an-code-color": "#d4d4d4",
      "--an-attachment-background": "#242424",
      "--an-attachment-border-color": "#2a2a2a",
      "--an-attachment-hover-background": "#27272a",
      "--an-attachment-color": "#fafafa",
      "--an-attachment-color-muted": "#8c8c8c",
      "--an-scrollbar-color": "rgba(255,255,255,0.12)",
      "--an-scrollbar-hover-color": "rgba(255,255,255,0.2)",
      "--an-primary-color": "#ef4444",
      "--an-primary-color-hover": "#d23c3c",
      "--an-primary-color-active": "#bf3636",
      "--an-focus-color": "#ef4444",
      "--an-send-button-color": "#1a1a1a",
      "--an-send-button-bg": "#ef4444",
      "--an-send-button-hover-color": "#1a1a1a",
      "--an-send-button-hover-bg": "#d23c3c",
      "--an-send-button-active-bg": "#bf3636",
      "--an-send-button-shadow": "none",
      "--an-input-focus-border-color": "#ef4444",
      "--an-input-focus-shadow": "0 0 0 2px #ef44441a",
      "--an-diff-added-bg": "rgba(34, 197, 94, 0.15)",
      "--an-diff-added-border": "rgba(34, 197, 94, 0.4)",
      "--an-diff-added-text": "#4ade80",
      "--an-diff-removed-bg": "rgba(239, 68, 68, 0.15)",
      "--an-diff-removed-border": "rgba(239, 68, 68, 0.4)",
      "--an-diff-removed-text": "#f87171",
    },
  },

  cursor: {
    theme: {
      "--an-font-family": "system-ui, sans-serif",
      "--an-font-weight": "400",
      "--an-font-weight-medium": "500",
      "--an-font-weight-semibold": "600",
      "--an-text-size": "13px",
      "--an-text-size-sm": "13px",
      "--an-text-size-xs": "11px",
      "--an-line-height": "1.6",
      "--an-border-radius": "12px",
      "--an-message-border-radius": "12px",
      "--an-input-border-radius": "12px",
      "--an-input-inner-border-radius": "4px",
      "--an-send-button-border-radius": "9999px",
      "--an-stop-button-border-radius": "9999px",
      "--an-mode-selector-border-radius": "4px",
      "--an-tool-border-radius": "4px",
      "--an-code-border-radius": "4px",
      "--an-attachment-border-radius": "4px",
      "--an-message-gap": "16px",
      "--an-user-message-padding": "12px 16px",
      "--an-input-padding": "12px 16px",
      "--an-tool-padding": "8px 12px",
      "--an-code-padding": "16px",
      "--an-send-button-size": "32px",
      "--an-stop-button-size": "32px",
      "--an-scrollbar-width": "6px",
      "--an-input-font-size": "13px",
      "--an-date-divider-font-size": "11px",
      "--an-model-selector-font-size": "12px",
      "--an-tool-font-size": "13px",
      "--an-code-font-size": "13px",
      "--an-code-font-family": "ui-monospace, monospace",
      "--an-attachment-font-size": "12px",
      "--an-message-style": "full-width",
      "--an-message-density": "relaxed",
      "--an-input-style": "flat",
      "--an-send-button-style": "circle-icon",
      "--an-stop-button-style": "circle-square",
      "--an-sticky-user-messages": "true",
      "--an-show-date-divider": "false",
      "--an-show-copy-button": "true",
      "--an-text-contrast": "normal",
      "--an-input-placeholder": "Plan, search, or ask...",
      "--an-attachment-button-style": "paperclip",
      "--an-attachment-preview-style": "chip",
      "--an-tool-call-style": "compact",
      "--an-thinking-display": "streaming",
      "--an-code-action-display": "diff-card",
      "--an-bash-display": "terminal-card",
      "--an-search-display": "minimal",
      "--an-show-tool-icons": "false",
      "--an-message-shadow": "false",
      "--an-input-fill": "true",
      "--an-input-shadow-toggle": "false",
      "--an-show-window-chrome": "false",
      "--an-max-width": "420px",
      "--an-attachment-button-position": "right",
      "--an-model-selector-position": "input-bar",
      "--an-model-selector-side": "left",
      "--an-mode-selector-position": "inline",
    },
    light: {
      "--an-background": "#ffffff",
      "--an-background-secondary": "#f0f0f0",
      "--an-background-tertiary": "#f8f8f8",
      "--an-foreground": "#1a1a1a",
      "--an-foreground-muted": "#737373",
      "--an-foreground-subtle": "#a3a3a3",
      "--an-border-color": "#e4e4e7",
      "--an-border-color-light": "#ededf0",
      "--an-message-shadow": "none",
      "--an-user-message-bg": "#f5f5f5",
      "--an-user-message-text": "#1a1a1a",
      "--an-date-divider-color": "#a3a3a3",
      "--an-date-divider-border-color": "#ededf0",
      "--an-input-background": "#ffffff",
      "--an-input-border-color": "#ededf0",
      "--an-input-color": "#1a1a1a",
      "--an-input-placeholder-color": "#a3a3a3",
      "--an-input-shadow": "none",
      "--an-stop-button-color": "#ffffff",
      "--an-stop-button-bg": "#1a1a1a",
      "--an-mode-selector-background": "#f0f0f0",
      "--an-mode-selector-color": "#737373",
      "--an-mode-selector-active-color": "#1a1a1a",
      "--an-mode-selector-active-background": "#ffffff",
      "--an-model-selector-color": "#737373",
      "--an-model-selector-hover-color": "#1a1a1a",
      "--an-tool-background": "#f8f8f8",
      "--an-tool-border-color": "#e4e4e7",
      "--an-tool-color": "#1a1a1a",
      "--an-tool-color-muted": "#737373",
      "--an-tool-icon-color": "#737373",
      "--an-code-background": "#1e1e1e",
      "--an-code-color": "#d4d4d4",
      "--an-attachment-background": "#f0f0f0",
      "--an-attachment-border-color": "#e4e4e7",
      "--an-attachment-hover-background": "#ebebeb",
      "--an-attachment-color": "#1a1a1a",
      "--an-attachment-color-muted": "#737373",
      "--an-scrollbar-color": "rgba(0,0,0,0.12)",
      "--an-scrollbar-hover-color": "rgba(0,0,0,0.2)",
      "--an-primary-color": "#3C7CAB",
      "--an-primary-color-hover": "#356d96",
      "--an-primary-color-active": "#306389",
      "--an-focus-color": "#3C7CAB",
      "--an-send-button-color": "#1a1a1a",
      "--an-send-button-bg": "#3C7CAB",
      "--an-send-button-hover-color": "#1a1a1a",
      "--an-send-button-hover-bg": "#356d96",
      "--an-send-button-active-bg": "#306389",
      "--an-send-button-shadow": "none",
      "--an-input-focus-border-color": "#3C7CAB",
      "--an-input-focus-shadow": "0 0 0 2px #3C7CAB1a",
      "--an-diff-added-bg": "rgba(34, 197, 94, 0.1)",
      "--an-diff-added-border": "rgba(34, 197, 94, 0.5)",
      "--an-diff-added-text": "#15803d",
      "--an-diff-removed-bg": "rgba(239, 68, 68, 0.1)",
      "--an-diff-removed-border": "rgba(239, 68, 68, 0.5)",
      "--an-diff-removed-text": "#dc2626",
    },
    dark: {
      "--an-background": "#0a0a0a",
      "--an-background-secondary": "#242424",
      "--an-background-tertiary": "#141414",
      "--an-foreground": "#fafafa",
      "--an-foreground-muted": "#8c8c8c",
      "--an-foreground-subtle": "#71717a",
      "--an-border-color": "#2a2a2a",
      "--an-border-color-light": "#1f1f1f",
      "--an-message-shadow": "none",
      "--an-user-message-bg": "#242424",
      "--an-user-message-text": "#ffffff",
      "--an-date-divider-color": "#71717a",
      "--an-date-divider-border-color": "#1f1f1f",
      "--an-input-background": "#0a0a0a",
      "--an-input-border-color": "#1f1f1f",
      "--an-input-color": "#fafafa",
      "--an-input-placeholder-color": "#71717a",
      "--an-input-shadow": "none",
      "--an-stop-button-color": "#0a0a0a",
      "--an-stop-button-bg": "#fafafa",
      "--an-mode-selector-background": "#242424",
      "--an-mode-selector-color": "#8c8c8c",
      "--an-mode-selector-active-color": "#fafafa",
      "--an-mode-selector-active-background": "#141414",
      "--an-model-selector-color": "#8c8c8c",
      "--an-model-selector-hover-color": "#fafafa",
      "--an-tool-background": "#141414",
      "--an-tool-border-color": "#2a2a2a",
      "--an-tool-color": "#fafafa",
      "--an-tool-color-muted": "#8c8c8c",
      "--an-tool-icon-color": "#8c8c8c",
      "--an-code-background": "#0a0a0a",
      "--an-code-color": "#d4d4d4",
      "--an-attachment-background": "#242424",
      "--an-attachment-border-color": "#2a2a2a",
      "--an-attachment-hover-background": "#27272a",
      "--an-attachment-color": "#fafafa",
      "--an-attachment-color-muted": "#8c8c8c",
      "--an-scrollbar-color": "rgba(255,255,255,0.12)",
      "--an-scrollbar-hover-color": "rgba(255,255,255,0.2)",
      "--an-primary-color": "#81A1C1",
      "--an-primary-color-hover": "#728eaa",
      "--an-primary-color-active": "#67819a",
      "--an-focus-color": "#81A1C1",
      "--an-send-button-color": "#1a1a1a",
      "--an-send-button-bg": "#81A1C1",
      "--an-send-button-hover-color": "#1a1a1a",
      "--an-send-button-hover-bg": "#728eaa",
      "--an-send-button-active-bg": "#67819a",
      "--an-send-button-shadow": "none",
      "--an-input-focus-border-color": "#81A1C1",
      "--an-input-focus-shadow": "0 0 0 2px #81A1C11a",
      "--an-diff-added-bg": "rgba(34, 197, 94, 0.15)",
      "--an-diff-added-border": "rgba(34, 197, 94, 0.4)",
      "--an-diff-added-text": "#4ade80",
      "--an-diff-removed-bg": "rgba(239, 68, 68, 0.15)",
      "--an-diff-removed-border": "rgba(239, 68, 68, 0.4)",
      "--an-diff-removed-text": "#f87171",
    },
  },
};
